name: CICD
on: 
  pull_request:
    branches: 
      - "main"        # Aciona quando há um PR fechado (merge) para a branch main
      - "develop"     # Aciona quando há um PR fechado (merge) para a branch develop
    types: [closed]   # Somente quando o PR é fechado
  workflow_dispatch:  # Permite acionar manualmente, se necessário
    
jobs:
  CI:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

  CD-Dev:
    # Condição para rodar somente se o PR for para a branch develop
    if: github.ref == 'refs/heads/develop'
    needs: [CI]
    uses: wallafi01/dotnet/.github/workflows/deploy.yml@develop 
    with:
      environment: dev
    secrets: inherit

  CD-Prod:
    # Condição para rodar somente se o PR for para a branch main
    if: github.ref == 'refs/heads/main'
    needs: [CI]
    uses: wallafi01/dotnet/.github/workflows/deploy.yml@main    
    with:
      environment: prod
    secrets: inherit
