name: CICD
on: 
  pull_request:
    branches: ["main", "develop"] 
    types: [closed]
  workflow_dispatch:
    
jobs:
  CI:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

  CD-Dev:
    if: github.ref == 'refs/heads/develop'
    needs: [CI]
    uses: wallafi01/dotnet/.github/workflows/deploy.yml@main  # Ajuste a branch para main ou develop conforme necessário
    with:
      environment: dev
    secrets: inherit

  CD-Prod:
    if: github.ref == 'refs/heads/main'
    needs: [CI]
    uses: wallafi01/dotnet/.github/workflows/deploy.yml@main  # Ajuste a branch para main ou develop conforme necessário
    with:
      environment: prod
    secrets: inherit
